### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by h-er0** [Merrit/unicode_emojis#3]
how I can retrieve emojis by categories ?
Smileys & People.
Animals & Nature.
Food & Drink.
Activity.
Travel & Places.
 Objects.
Symbols.
Flags.

**Comment by Merrit** [comment]
```dart
final smilies = UnicodeEmojis.allEmojis
      .where((emoji) => emoji.category == Category.smileysAndEmotion)
      .toList();
```

It would probably be good to add built-in syntactic sugar to make this easier, I will look at doing so if I can find some time. :)

**Comment by h-er0** [comment]
> ```dart
> final smilies = UnicodeEmojis.allEmojis
>       .where((emoji) => emoji.category == Category.smileysAndEmotion)
>       .toList();
> ```
> 
> It would probably be good to add built-in syntactic sugar to make this easier, I will look at doing so if I can find some time. :)

Thx for the answer

**Comment by Merrit** [comment]
I created #4 to track the issue.
